### ISSUE TITLE
Compiler doesn't produce outfile

### ISSUE THREAD

**Issue by rafi007akhtar** [aalhour/PyCOOLC#13]
**Bug.** The compiler `pycoolc` doesn't generate outfile when using the `--outfile` option.

**Description.** I installed `pycoolc` on my Linux Ubuntu system, and it installed correctly. Then, I tried to compile a simple "hello world" program in COOL using `pycoolc`, and it compiled. But when I used pycoolc to generate an outfile so that I could run it using `spim`, it didn't generate any.

**Terminal interaction.** This is _exactly_ what happened when I tried using your compiler on my `hello.cl` file:

```sh
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# # Finding all files staring with 'h'
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# find h*
hello.cl
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# # hello.cl exists; now compiling using pycoolc
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# pycoolc hello.cl
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# # compiled; now generating outfile
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# pycoolc hello.cl --outfile helloAsm.s
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# # Let's see if this file exists
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# find h*
hello.cl
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# find helloAsm.s
find: ‘helloAsm.s’: No such file or directory
root@rafier:/media/rafi007akhtar/Stuff/UEM/Sem 7 Stuff/COOL# # Clearly, compiler doesn't generate outfile
```
In case you're interested, here is source code of [`hello.cl`](https://github.com/rafi007akhtar/COOL/blob/master/hello.cl).

Looking forward to seeing the issue resolved!

**Comment by aalhour** [comment]
Hi @rafi007akhtar,

The compiler is not complete yet. Check the Dev-Status section on the README doc for more information: https://github.com/aalhour/PyCOOLC#dev-status

Cheers,
Ahmad
